//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.29 at 07:23:58 PM IST 
//

package org.fireweb.web.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for fireweb-config complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="fireweb-config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="handlers" type="{http://www.fireweb.org/web/config}handlers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fireweb-config", propOrder = { "handlers" })
@XmlRootElement(name = "fireweb-config")
public class FirewebConfig {

	@XmlElement(required = true)
	protected Handlers handlers;

	/**
	 * Gets the value of the handlers property.
	 * 
	 * @return possible object is {@link Handlers }
	 * 
	 */
	public Handlers getHandlers() {
		return handlers;
	}

	/**
	 * Sets the value of the handlers property.
	 * 
	 * @param value allowed object is {@link Handlers }
	 * 
	 */
	public void setHandlers(Handlers value) {
		this.handlers = value;
	}

}
