//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.29 at 07:23:58 PM IST 
//


package org.fireweb.web.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.fireweb.web.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FirewebConfig_QNAME = new QName("http://www.fireweb.org/web/config", "fireweb-config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.fireweb.web.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FirewebConfig }
     * 
     */
    public FirewebConfig createFirewebConfig() {
        return new FirewebConfig();
    }

    /**
     * Create an instance of {@link Handler }
     * 
     */
    public Handler createHandler() {
        return new Handler();
    }

    /**
     * Create an instance of {@link Handlers }
     * 
     */
    public Handlers createHandlers() {
        return new Handlers();
    }

    /**
     * Create an instance of {@link Forward }
     * 
     */
    public Forward createForward() {
        return new Forward();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FirewebConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fireweb.org/web/config", name = "fireweb-config")
    public JAXBElement<FirewebConfig> createFirewebConfig(FirewebConfig value) {
        return new JAXBElement<FirewebConfig>(_FirewebConfig_QNAME, FirewebConfig.class, null, value);
    }

}
