//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.31 at 11:54:27 AM IST 
//

package org.fireweb.web2.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for fireweb2config complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="fireweb2config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="handler-mapping" type="{http://www.fireweb.org/web2/config}handler-mapping"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fireweb2config", propOrder = { "handlerMapping" })
@XmlRootElement(name = "fireweb2config")
public class Fireweb2Config {

	@XmlElement(name = "handler-mapping", required = true)
	protected HandlerMapping handlerMapping;

	/**
	 * Gets the value of the handlerMapping property.
	 * 
	 * @return possible object is {@link HandlerMapping }
	 * 
	 */
	public HandlerMapping getHandlerMapping() {
		return handlerMapping;
	}

	/**
	 * Sets the value of the handlerMapping property.
	 * 
	 * @param value allowed object is {@link HandlerMapping }
	 * 
	 */
	public void setHandlerMapping(HandlerMapping value) {
		this.handlerMapping = value;
	}

}
