//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.31 at 11:54:27 AM IST 
//


package org.fireweb.web2.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.fireweb.web2.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fireweb2Config_QNAME = new QName("http://www.fireweb.org/web2/config", "fireweb2config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.fireweb.web2.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Fireweb2Config }
     * 
     */
    public Fireweb2Config createFireweb2Config() {
        return new Fireweb2Config();
    }

    /**
     * Create an instance of {@link Handler }
     * 
     */
    public Handler createHandler() {
        return new Handler();
    }

    /**
     * Create an instance of {@link HandlerMapping }
     * 
     */
    public HandlerMapping createHandlerMapping() {
        return new HandlerMapping();
    }

    /**
     * Create an instance of {@link Forward }
     * 
     */
    public Forward createForward() {
        return new Forward();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fireweb2Config }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fireweb.org/web2/config", name = "fireweb2config")
    public JAXBElement<Fireweb2Config> createFireweb2Config(Fireweb2Config value) {
        return new JAXBElement<Fireweb2Config>(_Fireweb2Config_QNAME, Fireweb2Config.class, null, value);
    }

}
